//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714bbruce2h
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public int Id { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual RentalTool RentalTool { get; set; }
    }
}
